import extractMessageFromTraceEvent from '@/components/SynapseChat/extractMessageFromTraceEvent'

// Message from real trace generated by Sonnet 4 via Bedrock.
const message = {
  output: {
    message: {
      role: 'assistant',
      content: [
        {
          text: null,
          image: null,
          document: null,
          video: null,
          toolUse: null,
          toolResult: null,
          guardContent: null,
          cachePoint: null,
          reasoningContent: {
            reasoningText: {
              text: 'The user wants to know about row 1 in the grid. To provide information about a specific row, I need to query the grid to retrieve data for that row. I should use the query function to get the data for row 1. \n\nHowever, I need to be careful about how I target "row 1". In grid systems, rows might be identified by their position (offset) or by a specific row ID. Since the user said "row 1", they likely mean the first row in the current view/dataset.\\n\\nI should query for a single row with a limit of 1 and offset of 0 (which would be the first row), and select all columns to get complete information about that row. I\'ll also need to check if there are any validation issues with that row.\\n\\nLet me construct a query to get the first row with all columns selected.',
              signature:
                'EqcHCkgICRABGAIqQNExRf+0hWVhDET9K3vO8S4Qtl3LZlz12jOtgtnpbHQ2MSpDpyq65tQqpsW9mxmXyop8Bd5NXlRYcYoDGivrma0SDGP2hhtKrzwu17ynJBoMc+c08fLIteMxUmAGIjDRUVf1+QV8yF6coGEtYTMsO+2lHWR8vsHcDAws/PQWP+uwYKdzAfkvUt5m6vhhD5MqjAZWZwvOGiu0VXSPB/G/xHa1WXbG+DilFweba8Yx9w2Ilbb6a+XyHMYm4HK4g8s8FiwRHlwplgZrod0Bdae2Dt1DGEo1mJpyuf6WFK1ugiUjAQ8dcT9TakJkqPzYqRE1RBL55sB3dzHkXO2czwGzzQEx4Cc6XO7UzbLlWZucasxcXNp8/CyWyfaOKd85piO/+JuT4RxdLfgNYvVpMQIN+iBMgl12N/euqMSSHoWfupNchSTXjg7Jf4V8dp2jhwahhE48uD0VfpZopQEv7IOIByFSMdi+xiTjwFomBWfEQVCegA/ZUlX5wsqYhgHXIdQJm9SK8/5AN/Nfj84rC7WOVjS/70KFt5Idmgltn7aYGsZpbBml+e6zdSfhc60ipXOmb1UU64KBqwcxcS9gXKB7UFffGhjFT8wvErm7dGz7NwNwssQ34hqWJlgPt8Sb8nLe9vLnyHhOZmQRnjihTV6hZJZfQf0Bwmsdp0X5TE/kqfDqf6cl3BQ16QFpsf/oXDYusZNQTMsBPkNdBpv7pK8hhBJ0d0vbHWxw61gkXmK+LaA8cXmc6IDbW2WHRANaMQJx6FWVEsuREVN6HpPFiBdvK2IqT19w2nMTiFk+woGqhND4laKx9zlstj56jIisuj8Q6Q+sP0dlXd2h4rB5jGXS2lrEuq1zFwpu8FaWnSVFigPqGixaUf4cfmjkZBvAKnRRR5k213ywPdlh+wq2HlIJBN/HFgc8iYKN5kEKH05o/V7YMUMv+OqSnnUNtNjMBdpCvsJ3vNrMp5GycFCWQe6i+hcnh5AQuzreBDZNraC5JlWZGgmg8WcrTSaGaUxyuvz8I4lXArV35rIQOzztgtpBsDOjlZiI/xhSa87TsEgrlzUVEKKQTdviRV8vFeeA8/Z4Lk5eIe2LcvSzLYU7RpbQLRnN8e9S1LiTTnRSiSAagXO02rEpqL8mL6rJFP9Wb4c+WQKXjGPW/0q0TLU9GD3DpcRkEtuQ0ecN8q15nM15uGg1jK+z7zivfE9LzzLylA5/0TeQo0/fMnMwO1laDssYAQ==',
            },
            redactedContent: null,
          },
          citationsContent: null,
        },
        {
          text: "I'll retrieve information about row 1 for you. Let me query the grid to get the data and any validation status for that row.",
          image: null,
          document: null,
          video: null,
          toolUse: null,
          toolResult: null,
          guardContent: null,
          cachePoint: null,
          reasoningContent: null,
          citationsContent: null,
        },
        {
          text: null,
          image: null,
          document: null,
          video: null,
          toolUse: {
            toolUseId: 'tooluse_SR8E9G2oT0-IbQxzYElLmQ',
            name: 'PUT__org_sage_grid_one__put_repo_v1_grid_query',
            input: {
              query: {
                columnSelection: [
                  {
                    concreteType:
                      'org.sagebionetworks.repo.model.grid.query.SelectAll',
                  },
                ],
                offset: 0,
                limit: 1,
              },
            },
            type: null,
          },
          toolResult: null,
          guardContent: null,
          cachePoint: null,
          reasoningContent: null,
          citationsContent: null,
        },
      ],
    },
  },
  stopReason: 'tool_use',
  usage: {
    inputTokens: 4561,
    outputTokens: 331,
    totalTokens: 4892,
    cacheReadInputTokenCount: null,
    cacheWriteInputTokenCount: null,
    cacheReadInputTokens: 0,
    cacheWriteInputTokens: 0,
  },
  metrics: { latencyMs: 6335 },
  additionalModelResponseFields: null,
  trace: null,
  performanceConfig: null,
}

describe('extractMessageFromTraceEvent', () => {
  it('extracts reasoning and tool use messages from a trace event', () => {
    const actual = extractMessageFromTraceEvent({
      timestamp: 0,
      message: JSON.stringify(message),
    })

    expect(actual).toEqual([
      {
        reasoningText:
          'The user wants to know about row 1 in the grid. To provide information about a specific row, I need to query the grid to retrieve data for that row. I should use the query function to get the data for row 1. \n\nHowever, I need to be careful about how I target "row 1". In grid systems, rows might be identified by their position (offset) or by a specific row ID. Since the user said "row 1", they likely mean the first row in the current view/dataset.\\n\\nI should query for a single row with a limit of 1 and offset of 0 (which would be the first row), and select all columns to get complete information about that row. I\'ll also need to check if there are any validation issues with that row.\\n\\nLet me construct a query to get the first row with all columns selected.',
      },
      {
        toolName: 'PUT__org_sage_grid_one__put_repo_v1_grid_query',
        toolInput: {
          query: {
            columnSelection: [
              {
                concreteType:
                  'org.sagebionetworks.repo.model.grid.query.SelectAll',
              },
            ],
            offset: 0,
            limit: 1,
          },
        },
      },
    ])
  })
})
