packages:
  - apps/**/*
  - packages/*
catalog:
  "@apidevtools/json-schema-ref-parser": ^9.1.2
  "@aws-sdk/client-s3": ^3.803.0
  "@aws-sdk/lib-storage": ^3.803.0
  "@babel/cli": ^7.27.2
  "@babel/core": ^7.27.1
  "@babel/plugin-proposal-class-properties": ^7.18.6
  "@babel/plugin-proposal-object-rest-spread": ^7.20.7
  "@babel/plugin-syntax-dynamic-import": ^7.8.3
  "@babel/plugin-transform-react-jsx": ^7.27.1
  "@babel/plugin-transform-runtime": ^7.27.1
  "@babel/preset-env": ^7.27.2
  "@babel/preset-react": ^7.27.1
  "@babel/preset-typescript": ^7.27.1
  "@babel/runtime": ^7.27.1
  "@babel/types": ^7.27.1
  "@brainhubeu/react-carousel": 1.19.26
  "@emotion/core": ^11.0.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.0
  "@eslint/compat": ^1.2.9
  "@eslint/eslintrc": ^3.3.1
  "@eslint/js": ^9.26.0
  "@faker-js/faker": ^8.4.1
  "@googlemaps/jest-mocks": ^2.22.6
  "@jest/reporters": ^29.7.0
  "@juggle/resize-observer": ^3.4.0
  "@mui/icons-material": ^5.17.1
  "@mui/material": ^5.17.1
  "@mui/system": ^5.17.1
  "@mui/utils": ^5.17.1
  "@mui/x-data-grid": ^6.20.4
  "@mui/x-date-pickers": ^6.20.2
  "@open-draft/deferred-promise": ^2.2.0
  "@openapitools/openapi-generator-cli": ^2.20.0
  "@playwright/test": ^1.52.0
  "@popperjs/core": ^2.11.8
  "@react-google-maps/api": ^2.20.6
  "@react-hook/resize-observer": ^1.2.6
  "@react-hookz/web": ^23.1.0
  "@rjsf/core": 5.24.8
  "@rjsf/mui": 5.24.8
  "@rjsf/utils": 5.24.8
  "@rjsf/validator-ajv8": 5.24.8
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-node-resolve": ^15.3.1
  "@rollup/plugin-terser": ^0.4.4
  "@storybook/addon-actions": ^8.6.12
  "@storybook/addon-designs": ^8.2.1
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-links": ^8.6.12
  "@storybook/addon-themes": ^8.6.12
  "@storybook/manager-api": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@storybook/theming": ^8.6.12
  "@svgr/plugin-jsx": ^8.1.0
  "@tanstack/query-core": 5.22.2
  "@tanstack/react-query": 5.22.2
  "@tanstack/react-query-devtools": 5.24.0
  "@tanstack/react-table": ^8.21.3
  "@tanstack/react-virtual": ^3.13.8
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/user-event": ^14.6.1
  "@types/brainhubeu__react-carousel": 1.15.0
  "@types/dagre": ^0.7.52
  "@types/google.maps": ^3.58.1
  "@types/history": ^4.7.11
  "@types/isomorphic-fetch": ^0.0.36
  "@types/jest": ^29.5.14
  "@types/jest-when": ^3.5.5
  "@types/jquery": ^3.5.32
  "@types/json-schema": ^7.0.15
  "@types/jsonpath": ^0.2.4
  "@types/lodash": ^4.17.16
  "@types/markdown-it": ^13.0.9
  "@types/minimist": ^1.2.5
  "@types/node": ^20.17.41
  "@types/papaparse": ^5.3.15
  "@types/plotly.js": ^2.35.5
  "@types/plotly.js-basic-dist": ^1.54.4
  "@types/pluralize": ^0.0.29
  "@types/qrcode": ^1.5.5
  "@types/react": 18.3.12
  "@types/react-addons-css-transition-group": ^15.0.10
  "@types/react-dom": 18.3.1
  "@types/react-easy-crop": ^2.0.0
  "@types/react-mailchimp-subscribe": ^2.1.4
  "@types/react-plotly.js": ^2.6.3
  "@types/react-tooltip": ^4.2.4
  "@types/react-transition-group": ^4.4.12
  "@types/react-virtualized-auto-sizer": ^1.0.8
  "@types/react-window": ^1.8.8
  "@types/shortid": ^0.0.29
  "@types/spark-md5": ^3.0.5
  "@types/tinycolor2": ^1.4.6
  "@types/ua-parser-js": ^0.7.39
  "@types/xml2js": ^0.4.14
  "@upsetjs/react": ^1.11.0
  "@vitejs/plugin-react": ^4.4.1
  "@vitest/coverage-v8": ^1.6.1
  "@vitest/ui": ^1.6.1
  "@vitest/utils": ^1.6.1
  "@welldone-software/why-did-you-render": ^8.0.3
  animate.css: ^4.1.1
  assert: ^2.1.0
  babel-jest: ^29.7.0
  babel-loader: ^9.2.1
  buffer: ^6.0.3
  c8: ^8.0.1
  chromatic: ^11.28.2
  classnames: ^2.5.1
  clone-deep: ^4.0.1
  copyfiles: ^2.4.1
  core-js: ^3.42.0
  dagre: ^0.8.5
  dayjs: ^1.11.13
  dompurify: ^3.2.5
  dotenv: ^16.5.0
  dotenv-cli: ^7.4.4
  eslint: ^9.26.0
  eslint-plugin-barrel-files: ^2.1.1
  eslint-plugin-jest: ^28.11.0
  eslint-plugin-jest-dom: ^5.5.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^0.11.6
  eslint-plugin-testing-library: ^7.1.1
  https-browserify: ^1.0.0
  husky: ^9.1.7
  identity-obj-proxy: ^3.0.0
  immutable: 4.1.0
  isomorphic-fetch: ^3.0.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-fail-on-console: ^3.3.1
  jest-html-reporter: ^3.10.2
  jest-when: ^3.7.0
  jotai: ^2.12.4
  jotai-devtools: ^0.6.3
  jsdom: ^21.1.2
  json-rules-engine: ^4.1.0
  jsonpath: ^1.1.1
  katex: ^0.16.22
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  markdown-it-br: ^1.0.0
  markdown-it-center-text: ^1.0.4
  markdown-it-inline-comments: ^1.0.1
  markdown-it-strikethrough-alt: ^1.0.0
  markdown-it-sub-alt: ^1.0.0
  markdown-it-sup-alt: ^1.0.2
  markdown-it-synapse-heading: ^1.0.1
  markdown-it-synapse-math: ^3.0.5
  memfs: ^3.5.3
  minimist: ^1.2.8
  mocha: ^10.8.2
  msw-storybook-addon: ^1.10.0
  mui-one-time-password-input: ^2.0.3
  nx: 19.7.3
  object-assign: ^4.1.1
  p-limit: ^6.2.0
  papaparse: ^5.5.2
  path-browserify: ^1.0.1
  plotly.js: 2.28.0
  plotly.js-basic-dist: ^2.35.3
  pluralize: ^8.0.0
  postcss-normalize: ^10.0.1
  prettier: ^2.8.8
  process: ^0.11.10
  qrcode: ^1.5.4
  raf: ^3.4.1
  react: ^18.3.1
  react-cookie: 4.0.0
  react-datetime: ^3.3.1
  react-dom: ^18.3.1
  react-easy-crop: ^5.4.1
  react-error-boundary: ^3.1.4
  react-hot-toast: 2.2.0
  react-inspector: ^6.0.2
  react-intersection-observer: ^9.16.0
  react-mailchimp-subscribe: ^2.1.3
  react-plotly.js: ^2.6.0
  react-popper: ^2.3.0
  react-reflex: ^4.2.7
  react-router: ^7.5.3
  react-select: ^5.10.1
  react-select-event: ^5.5.1
  react-sizeme: ^3.0.2
  react-spinners: ^0.13.8
  react-switch: ^7.1.0
  react-test-renderer: ^18.3.1
  react-transition-group: ^4.4.5
  react-type-animation: ^3.2.0
  react-virtualized-auto-sizer: ^1.0.26
  react-vtree: 3.0.0-beta.3
  react-window: ^1.8.11
  reactflow: ^11.11.4
  rimraf: ^5.0.10
  rollup: ^4.40.2
  rss-parser: ^3.13.0
  sass: ^1.87.0
  schema-dts: ^1.1.5
  shortid: ^2.2.17
  source-map-explorer: ^2.5.3
  spark-md5: ^3.0.2
  storybook: ^8.6.12
  stream-browserify: ^3.0.0
  stream-http: ^3.2.0
  svgo: ^3.3.2
  timers-browserify: ^2.0.12
  tinycolor2: ^1.6.0
  tslib: ^2.8.1
  tsup: ^8.4.0
  tsx: ^4.19.4
  type-fest: ^4.41.0
  typescript-eslint: ^8.32.0
  ua-parser-js: ^1.0.40
  undici: ^6.21.2
  universal-cookie: ^4.0.4
  url: ^0.11.4
  use-deep-compare-effect: ^1.8.1
  util: ^0.12.5
  vite: ^5.4.19
  vite-plugin-dts: ^4.5.3
  vite-plugin-externalize-deps: ^0.8.0
  vite-plugin-html: ^3.2.2
  vite-plugin-node-polyfills: 0.17.0
  vite-plugin-svgr: ^4.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^1.6.1
  weak-napi: ^2.0.2
  whatwg-fetch: ^3.6.20
  xss: ^1.0.15
  zod: ^3.24.4
