packages:
  - 'apps/**/*'
  - 'packages/*'
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@sage-bionetworks/*'
catalog:
  vite: ^8.0.16
  "@vitejs/plugin-react": ^6.0.2
  vitest: ^4.1.11
  "@vitest/coverage-v8": ^4.1.11
  "@vitest/ui": ^4.1.11
  "@vitest/utils": ^4.1.8
  "@vitest/spy": ^4.1.8
  "@vitest/browser-playwright": ^4.1.11
  react-router: ^7.18.0
  "@react-router/dev": ^7.18.0
  "@react-router/node": ^7.18.0
