packages:
  - 'apps/**/*'
  - 'packages/*'
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@sage-bionetworks/*'
registry: "https://registry.npmjs.org/"
"@sage-bionetworks:registry": "https://npm.pkg.github.com"
"//npm.pkg.github.com/:_authToken": "${GITHUB_TOKEN}"
