import {
  DST_TABLE_COLUMN_CONSTS,
  MANIFEST_COLUMN_CONSTS,
  ORG_TABLE_COLUMN_CONSTS,
} from '@/config/resources'

export default {
  [DST_TABLE_COLUMN_CONSTS.RELEVANT_ORG_NAMES]: 'Relevant Organizations',
  [DST_TABLE_COLUMN_CONSTS.MATURE]: 'Maturity',
  [DST_TABLE_COLUMN_CONSTS.RESPONSIBLE_ORG_LINKS]: 'Responsible Organizations',
  [DST_TABLE_COLUMN_CONSTS.RELEVANT_ORG_LINKS]: 'Relevant Organizations',
  [DST_TABLE_COLUMN_CONSTS.APPLICATION_COUNT]: 'AI Applications Count',
  [DST_TABLE_COLUMN_CONSTS.AI_APP_MARKDOWN]: 'AI Applications',
  standardName: 'Name of Standard',
  isOpen: 'Is Open?',
  registration: 'Requires Registration?',
  topic: 'Topics',

  [ORG_TABLE_COLUMN_CONSTS.NAME]: 'Name',
  [ORG_TABLE_COLUMN_CONSTS.ROR_ID]: 'ROR ID',
  [ORG_TABLE_COLUMN_CONSTS.WIKIDATA_ID]: 'Wikidata ID',
  [ORG_TABLE_COLUMN_CONSTS.SUBCLASS_OF]: 'Subclass Of',

  [MANIFEST_COLUMN_CONSTS.DATA_PART_NAME]: 'Data Type',
  [MANIFEST_COLUMN_CONSTS.DATA_PART_DESCRIPTION]: 'Description',
  [MANIFEST_COLUMN_CONSTS.STANDARDS_AND_TOOLS_LINKS]: 'Standards & Tools',
  [MANIFEST_COLUMN_CONSTS.USES_DATA_SUBSTRATES_LINKS]: 'Substrates',
  [MANIFEST_COLUMN_CONSTS.CONCERNS_DATA_TOPICS_LINKS]:
    'Standards Related to Topic',
  [MANIFEST_COLUMN_CONSTS.CONCERNS_DATA_TOPICS_DOC_LINKS]: 'Topics',
  [MANIFEST_COLUMN_CONSTS.ANATOMY_LINKS]: 'Anatomy',
  [MANIFEST_COLUMN_CONSTS.DATASETS_LINK]: 'Datasets',
}
