import ErrorPage, { SynapseErrorType } from './error/ErrorPage'
import NoContentAvailable from './SynapseTable/NoContentAvailable'

/**
 * NOTE: Avoid adding new components to this file -- import it directly instead of through index.ts
 * See https://tkdodo.eu/blog/please-stop-using-barrel-files
 */

export * from './AccessTokenPage'
export * from './AccountLevelBadges'
export * from './Authentication'
export * from './CardContainer'
export * from './CardContainerLogic'
export * from './CardGridWithLinks'
export * from './RowDataTable'
export * from './CertificationQuiz'
export * from './ChallengeDetailPage'
export * from './ChallengeDataDownload'
export * from './ChallengeSubmission'
export * from './ChangePassword'
export * from './ConfirmationDialog'
export * from './CookiesNotification'
export * from './CTASectionWrapper'
export * from './DownloadCart'
export * from './DynamicForm'
export * from './EntityBadgeIcons'
export * from './EntityDownloadConfirmation'
export * from './EntityFinder'
export * from './EntityForm'
export * from './error'
export * from './Evaluation'
export * from './ExperimentalMode'
export * from './ExternalFileHandleLink'
export * from './FileUpload'
export * from './FeaturedDataTabs'
export * from './FeaturedToolsList'
export * from './Forum'
export * from './FullWidthAlert'
export * from './GenericCard'
export * from './Goals'
export * from './GoalsV2'
export * from './GoalsV3'
export * from './GoogleAnalytics'
export * from './GoogleMap'
export * from './HasAccess'
export * from './Icon'
export * from './IconSvg'
export * from './Markdown/MarkdownCollapse'
export * from './Markdown/MarkdownEditor'
export * from './Markdown/MarkdownGithub'
export * from './ModalDownload'
export * from './OAuthClientManagement'
export * from './OrientationBanner'
export * from './Plot'
export * from './Programs'
export * from './ProgrammaticTableDownload'
export * from './ProvenanceGraph'
export * from './ProjectStorage'
export * from './QueryContext'
export * from './QueryCount'
export * from './QueryWrapper'
export * from './QueryWrapperPlotNav'
export * from './RegisterPageLogoutPrompt'
export * from './RenderIfInView'
export * from './Resources'
export * from './AccessRequirementAclEditor'
export * from './RssFeedCards'
export * from './ShowMore'
export * from './Skeleton'
export * from './StandaloneQueryWrapper'
export * from './styled'
export * from './SubscriptionPage'
export * from './SubsectionRowRenderer'
export * from './SynapseForm'
export * from './SynapseTable'
export * from './SynapseChat'
export * from './SystemUseNotification'
export * from './TableFeedCards'
export * from './TermsAndConditions'
export * from './TextField'
export * from './TimelinePlot'
export * from './ToastMessage'
export * from './UserCard'
export * from './UserCardList'
export * from './UserOrTeamBadge'
export * from './UserProfileLinks'
export * from './EntityHeaderTable'
export * from './AccessRequirementRelatedProjectsList'
export * from './HelpPopover'
export * from './MuiContainer'
export * from './JsonLdScript'
export * from './DatasetJsonLdScript'
export * from './SageResourcesPopover'
export * from './RecentPublicationsGrid'
export * from './ImageCardGridWithLinks'
export * from './PortalFeatureHighlights'
export * from './FeaturedResearch'
export * from './PortalHomePageHeader'
export * from './PortalFeaturedPartners'
export * from './PortalList'
export * from './PortalAclEditor'
export * from './PortalSectionHeader'

// TODO: Find a better way to expose Icon components
export { Project as ProjectIcon } from '@/assets/themed_icons/Project'
export { ErrorPage, SynapseErrorType }
export { NoContentAvailable }
