import { DetailsPageContent } from '@sage-bionetworks/synapse-portal-framework/components/DetailsPage/DetailsPageContentLayout'
import { useDetailsPageContext } from '@sage-bionetworks/synapse-portal-framework/components/DetailsPage/DetailsPageContext'
import { Box, Chip, Paper, Typography } from '@mui/material'
import MarkdownSynapse from 'synapse-react-client/components/Markdown/MarkdownSynapse'

// Synapse entity IDs of per-funder HTML dashboards generated by build_funder_dashboard.py.
// Update after running: python build_funder_dashboard.py --funder <FUNDER> --upload
const FUNDER_DASHBOARD_ENTITY_IDS: Record<string, string | null> = {
  NTAP: null,
  CTF: null,
  GFF: null,
}

// Snowflake-sourced aggregate stats — populate after pipeline runs.
// Keys match 180-day rolling window values.
type UsageStats = {
  downloads: string
  uniqueUsers: string
  egressGB: string
  avgDownloadsPerFile: string
  avgDownloadsPerDataset: string
  avgDownloadsPerProject: string
}
const FUNDER_STATS: Record<string, UsageStats | undefined> = {
  NTAP: undefined,
  CTF: undefined,
  GFF: undefined,
}

// ── Shared sub-components ──────────────────────────────────────────────────

function StatCard({
  value,
  label,
  chip,
  pending,
}: {
  value?: string
  label: string
  chip?: string
  pending?: boolean
}) {
  return (
    <Paper
      elevation={pending ? 1 : 2}
      sx={{
        p: 3,
        textAlign: 'center',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 0.75,
      }}
    >
      <Typography
        component="div"
        sx={{
          fontSize: '2.5rem',
          fontWeight: 700,
          lineHeight: 1,
          color: pending ? 'text.disabled' : 'text.primary',
        }}
      >
        {value ?? '—'}
      </Typography>
      <Typography variant="body2" color="text.secondary">
        {label}
      </Typography>
      {chip && (
        <Chip
          label={chip}
          size="small"
          sx={{ fontSize: 10, height: 18 }}
          color={chip === 'Snowflake' ? 'warning' : 'default'}
          variant="outlined"
        />
      )}
    </Paper>
  )
}

function SnowflakePlaceholder({
  title,
  description,
  height = 260,
}: {
  title: string
  description: string
  height?: number
}) {
  return (
    <Paper
      variant="outlined"
      sx={{
        height,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 1.5,
        px: 4,
        textAlign: 'center',
        bgcolor: 'grey.50',
      }}
    >
      <Chip label="Snowflake" size="small" color="warning" variant="outlined" />
      <Typography variant="subtitle2" color="text.secondary" fontWeight={700}>
        {title}
      </Typography>
      <Typography variant="body2" color="text.disabled" maxWidth={480}>
        {description}
      </Typography>
    </Paper>
  )
}

// ── Main tab component ─────────────────────────────────────────────────────

function OrganizationAnalyticsTab() {
  const { value: fundingAgency } = useDetailsPageContext('fundingAgency')

  if (fundingAgency == null) {
    return null
  }

  const dashboardEntityId = FUNDER_DASHBOARD_ENTITY_IDS[fundingAgency] ?? null
  const stats = FUNDER_STATS[fundingAgency]

  return (
    <DetailsPageContent
      content={[
        // ── Usage Summary ────────────────────────────────────────────────
        {
          id: 'Usage Summary',
          title: 'Usage Summary',
          element: (
            <Box>
              <Box
                display="grid"
                gridTemplateColumns="repeat(3, 1fr)"
                gap={2}
                mb={2}
              >
                <StatCard
                  value={stats?.downloads}
                  label="Total Downloads (180d)"
                  chip="Snowflake"
                  pending={!stats}
                />
                <StatCard
                  value={stats?.uniqueUsers}
                  label="Unique Users (180d)"
                  chip="Snowflake"
                  pending={!stats}
                />
                <StatCard
                  value={stats?.egressGB}
                  label="Data Egress GB (180d)"
                  chip="Snowflake"
                  pending={!stats}
                />
              </Box>

              {!stats && (
                <Box
                  sx={{
                    borderLeft: '4px solid',
                    borderLeftColor: 'warning.main',
                    bgcolor: 'warning.50',
                    borderRadius: 1,
                    p: 2,
                  }}
                >
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    gutterBottom
                  >
                    Download counts, unique users, and data egress are sourced
                    from the Snowflake analytics pipeline. Run the pipeline to
                    populate these values.
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    <code>
                      python build_funder_dashboard.py --funder {fundingAgency}{' '}
                      --upload
                    </code>
                  </Typography>
                </Box>
              )}
            </Box>
          ),
        },

        // ── Avg Downloads per File / Dataset / Project ────────────────────
        {
          id: 'Average Downloads',
          title: 'Average Downloads',
          element: (
            <Box display="grid" gridTemplateColumns="repeat(3, 1fr)" gap={2}>
              <StatCard
                value={stats?.avgDownloadsPerFile}
                label="Avg Downloads per File"
                chip="Snowflake"
                pending={!stats}
              />
              <StatCard
                value={stats?.avgDownloadsPerDataset}
                label="Avg Downloads per Dataset"
                chip="Snowflake"
                pending={!stats}
              />
              <StatCard
                value={stats?.avgDownloadsPerProject}
                label="Avg Downloads per Project"
                chip="Snowflake"
                pending={!stats}
              />
            </Box>
          ),
        },

        // ── Downloads by Assay Type (Figure 3) ───────────────────────────
        {
          id: 'Downloads by Assay Type',
          title: 'Downloads by Assay Type',
          element: dashboardEntityId ? (
            <MarkdownSynapse
              markdown={`\${preview?entityId=${dashboardEntityId}}`}
            />
          ) : (
            <SnowflakePlaceholder
              title="Representative assay types downloaded (Jan–Jun 2026)"
              description="Vertical bar chart of download counts by assay type (e.g. Microscopy, Immunofluorescence, RNA-seq). Ordered by download frequency. Sourced from Snowflake user download logs."
              height={300}
            />
          ),
        },

        // ── Downloads by Data Type ────────────────────────────────────────
        {
          id: 'Downloads by Data Type',
          title: 'Downloads by Data Type',
          element: (
            <SnowflakePlaceholder
              title="Downloads broken down by data type"
              description="Bar chart of download counts grouped by data type (Gene Expression, Genomic Variants, Drug Screen, etc.). Complements the assay-type breakdown for portfolio reporting."
              height={260}
            />
          ),
        },

        // ── Downloads by Institution Type ─────────────────────────────────
        {
          id: 'Downloads by Institution Type',
          title: 'Downloads by Institution Type',
          element: (
            <SnowflakePlaceholder
              title="Downloads by institution type (academia, nonprofit, industry, government)"
              description="Horizontal bar chart of download counts grouped by institution email domain (.edu, .org, .com, .gov, other). Shows which sector is most actively using this funder's data."
              height={220}
            />
          ),
        },

        // ── Project–User Network (Figure 4) ──────────────────────────────
        {
          id: 'Project–User Network',
          title: 'Project–User Network',
          element: (
            <SnowflakePlaceholder
              title="Network graph: funded projects (teal) connected to downloading users (pink)"
              description="Force-directed network graph where node size reflects number of connections. Reveals which projects attract the broadest user base and which users access multiple projects. Sourced from Snowflake download logs."
              height={360}
            />
          ),
        },

        // ── Cumulative Data Growth (Figure 6) ─────────────────────────────
        {
          id: 'Cumulative Data Growth',
          title: 'Cumulative Data Growth',
          element: (
            <SnowflakePlaceholder
              title="Cumulative data growth on the NF Data Portal (2016–2026)"
              description="Dual-axis line chart showing cumulative storage in TB (left axis, red) and total file count (right axis, blue) over time. Full portal scope — not filtered by funder."
              height={300}
            />
          ),
        },

        // ── Full embedded dashboard (when entity ID is set) ───────────────
        ...(dashboardEntityId
          ? [
              {
                id: 'Full Analytics Dashboard',
                title: 'Full Analytics Dashboard',
                element: (
                  <MarkdownSynapse
                    markdown={`\${preview?entityId=${dashboardEntityId}}`}
                  />
                ),
              },
            ]
          : []),
      ]}
    />
  )
}

export default OrganizationAnalyticsTab
