import { FacetColumnRequest } from './FacetColumnRequest'
import { QueryFilter } from './QueryFilter'

// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/table/SortDirection.html
export type SortItem = {
  column: string
  direction: '' | 'ASC' | 'DESC'
}

// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/table/Query.html
export type Query = {
  sql: string // The SQL query string
  selectedFacets?: FacetColumnRequest[] // The selected facet filters.
  includeEntityEtag?: boolean // Optional, default false. When true, a query results against views will
  // include the Etag of each entity in the results.
  offset?: number // The optional offset into the results
  limit?: number // The optional limit to the results
  sort?: SortItem[]
  additionalFilters?: QueryFilter[] // Appends additional filters to the SQL query.
  // These are applied before facets.
  // Filters within the list have an AND relationship.
  // If a WHERE clause already exists on the SQL query or facets are selected,
  // it will also be ANDed with the query generated by these additional filters.
  selectFileColumn?: number // The id of the column used to select file entities (e.g. to fetch the action required for download). The column needs to be an ENTITYID type column and be part of the schema of the underlying table/view.
  selectFileVersionColumn?: number //The id of the column used as the version for selecting file entities when required (e.g. to add a materialized view query to the download cart with version enabled). The column needs to be an INTEGER type column and be part of the schema of the underlying table/view.
}
