import { Box, Typography } from '@mui/material'
import { usePortalContext } from '../PortalContext'
import HeaderSearchBox from '../HeaderSearchBox'

const CancerComplexityHeader = () => {
  const { headerConfig } = usePortalContext()
  const { showBlur = true, centerText = false } = headerConfig
  const searchPlaceholder = 'Search for cancer related data and resources'
  const searchExampleTerms = [
    'Justo Turpis',
    'Fames',
    'Synapse Data',
    'Genomics',
  ]
  const content = (
    <>
      <Box
        className={`header-text ${showBlur ? 'blur' : ''} ${
          centerText ? 'center-text' : ''
        }`}
        sx={{
          margin: 0,
          padding: { xs: '40px', md: '40px 80px' },
        }}
      >
        <Typography
          variant="headline1"
          sx={{
            fontSize: '30px',
            fontWeight: 'bold',
            marginTop: '20px',
            marginBottom: '30px',
          }}
        >
          Welcome to the Cancer Complexity Knowledge Portal
        </Typography>
        <Typography variant="body1">
          The NCI Division of Cancer Biology supports multiple research programs
          composed of interdisciplinary communities of scientists who aim to
          integrate approaches, data, and tools to address important questions
          in basic and translational cancer research. Discover and download
          datasets, publications, and other resources generated by these
          programs.
        </Typography>
      </Box>
    </>
  )
  return (
    <header id="header">
      <div className="container-fluid">
        <Box
          className="row"
          sx={{
            display: 'flex',
            flexWrap: { xs: 'wrap', lg: 'nowrap' },
            justifyContent: 'center',
          }}
        >
          <Box
            className="col-md-offset-1 col-md-10"
            sx={{
              margin: 0,
              padding: { xs: '0 15px', lg: '20px 0' },
            }}
          >
            {content}
          </Box>
          <HeaderSearchBox
            searchExampleTerms={searchExampleTerms}
            searchPlaceholder={searchPlaceholder}
            path="/Search"
            sx={{
              '& > :first-child': {
                background: 'rgba(184, 204, 226, 0.60)',
              },
            }}
          />
        </Box>
      </div>
    </header>
  )
}

export default CancerComplexityHeader
