import { Stack, Typography } from '@mui/material'
import styles from './NamhubAbout.module.scss'
import { ReactComponent as AboutImage } from './assets/namhub-about.svg'
import { SectionLayout } from '../SectionLayout'

function NamhubAbout() {
  return (
    <div className={styles.aboutContainer}>
      <div className={styles.aboutImageContainer}>
        <AboutImage className={styles.aboutImage} />
      </div>
      <Stack className={styles.aboutTextContainer}>
        <div className={styles.aboutTitle}>
          <SectionLayout
            title="About New Approach Methodologies Hub"
            titleNode={
              <>
                About <b>N</b>ew <b>A</b>pproach <b>M</b>ethodologies Hub
              </>
            }
          />
        </div>
        <Typography variant="body1" className={styles.aboutTextColor}>
          NAMHub is the NAMs Data Hub and Coordinating Center for the NIH
          Complement-ARIE program, an initiative devoted to advancing the study
          of human biology and disease through technologies that do not rely on
          animal models. These technologies are known as NAMs, or New Approach
          Methodologies.
        </Typography>
        <Typography variant="body1" className={styles.aboutTextColor}>
          The NAMHub team includes data scientists, data engineers, modelers,
          and community engagement experts based at Sage Bionetworks and NYU
          Grossman School of Medicine.
        </Typography>
        <Typography variant="body1" className={styles.aboutTextColor}>
          Our mission is to make the complex data generated by NAMs, including
          organ-on-chip systems, computational models, and advanced cell-free
          chemistry assays, easier to compare, combine, and use for biomedical
          research. In this way, NAMHub helps researchers, clinicians,
          regulators, and technology developers turn human-relevant experimental
          systems into reliable resources for discovery, translation, and
          improved health.
        </Typography>
        <Typography variant="body1" className={styles.aboutTextColor}>
          Our long-term goal is to build the data foundation needed for NAMs to
          become trusted and widely used tools for understanding disease,
          evaluating therapies, and improving human health through alternatives
          to animal experimentation.
        </Typography>
      </Stack>
    </div>
  )
}

export default NamhubAbout
