import {
  AgentAccessLevel,
  AgentChatRequest,
  AgentChatResponse,
  AgentSession,
  CreateAgentSessionRequest,
  ListAgentSessionsRequest,
  ListAgentSessionsResponse,
  SessionHistoryResponse,
  TraceEventsResponse,
} from '@sage-bionetworks/synapse-types'

export const mockChatSessionId = 'session-456'
export const mockCreateAgentSessionRequest: CreateAgentSessionRequest = {
  agentAccessLevel: AgentAccessLevel.READ_YOUR_PRIVATE_DATA,
  agentRegistrationId: 'experimental-agent-123',
}
export const mockAgentSession: AgentSession = {
  sessionId: mockChatSessionId,
  agentAccessLevel: AgentAccessLevel.PUBLICLY_ACCESSIBLE,
  startedOn: '2024-09-01T12:00:00Z',
  agentRegistrationId: 'default-agent',
}
export const mockAgentSession2: AgentSession = {
  sessionId: 'session-789',
  agentAccessLevel: AgentAccessLevel.WRITE_YOUR_PRIVATE_DATA,
  startedOn: '2024-09-01T12:00:00Z',
  agentRegistrationId: 'default-agent',
}
export const mockListAgentSessionsRequest: ListAgentSessionsRequest = {
  nextPageToken: 'token-789',
}

export const mockListAgentSessionsResponse: ListAgentSessionsResponse = {
  page: [mockAgentSession, mockAgentSession2],
  nextPageToken: 'token-790',
}

export const mockAgentChatRequest: AgentChatRequest = {
  sessionId: mockChatSessionId,
  chatText: 'Hello! How can I access My Projects?',
  enableTrace: true,
}

export const mockAgentChatResponse: AgentChatResponse = {
  sessionId: mockChatSessionId,
  responseText:
    'This is the only response this agent is told to respond with.  \n\n<function_results>\n<result>\n<tool_name><REDACTED>_get_description</tool_name>\n<stdout>  **Adapt**: You can remix, transform, and build upon the material **Attribution:** You must acknowledge the Data Contributor using the acknowledgment statement below:  **Non-Commercial**: You may not use the material for commercial purposes. \n\nThe TOPACIO study was a phase 2 clinical trial of the investigational drug OPB-51602 in patients with advanced solid tumors. The study was sponsored by Oncopia Therapeutics, Inc. and conducted at multiple sites in the United States between 2013 and 2015.\n\nThis dataset contains de-identified clinical data, biomarker data, and pharmacokinetic/pharmacodynamic (PK/PD) data from the TOPACIO study. Specific data files include:\n\n- Demographics and baseline characteristics\n- Adverse events \n- Tumor response data\n- Pharmacokinetic data\n- Pharmacodynamic biomarker data\n\nThe data has been de-identified in accordance with HIPAA regulations. Please see the study protocol and data dictionary files for more details on the collected data and definitions.\n\n**Acknowledgment Statement**: The TOPACIO study data was contributed by Oncopia Therapeutics, Inc. Please use the following text to acknowledge the source of the data: "The results published here are in part based upon data generated by the TOPACIO clinical trial, provided by Oncopia Therapeutics, Inc."\n</stdout>\n</result>\n',
}

export const mockSessionHistoryResponse: SessionHistoryResponse = {
  sessionId: mockChatSessionId,
  page: [
    {
      usersRequestText: 'What is the weather like today?',
      usersRequestTimestamp: '2024-09-06T14:30:00Z',
      agentResponseText: 'The weather is sunny with a high of 75°F.',
      agentResponseTimestamp: '2024-09-06T14:30:10Z',
    },
    {
      usersRequestText: 'Can you tell me a joke?',
      usersRequestTimestamp: '2024-09-06T14:32:00Z',
      agentResponseText:
        'Why don’t scientists trust atoms? Because they make up everything!',
      agentResponseTimestamp: '2024-09-06T14:32:05Z',
    },
  ],
  nextPageToken: undefined,
}

export const mockTraceEventsResponse1: TraceEventsResponse = {
  jobId: ':id',
  page: [
    {
      timestamp: 1695567600, // Example timestamp (in seconds)
      message: 'Executing search on Synapse',
    },
  ],
}

export const mockTraceEventsResponse2: TraceEventsResponse = {
  jobId: ':id',
  page: [
    {
      timestamp: 1695567700, // Example timestamp (in seconds)
      message: 'Gathering entity metadata',
    },
  ],
}
export const mockTraceEventsResponse3: TraceEventsResponse = {
  jobId: ':id',
  page: [
    {
      timestamp: 1695567800, // Example timestamp (in seconds)
      message:
        '<thinking>The metadata shows that the entity with ID syn9602623 is a Synapse project named "SearchIntegrationTest.Projecte475c6e8-414a-4842-b876-bf8232ce05d0". Its description contains the search term "e7b33c3a-2392-4ce7-a357-efa4612e4a41". The metadata ...',
    },
  ],
}

// no new trace events events
export const mockEmptyTraceEventsResponse: TraceEventsResponse = {
  jobId: ':id',
  page: [],
}
