import {
  palette,
  generatePalette,
  adKnowledgePortalPalette,
  mtbPalette,
  arkPortalPalette,
  challengePortalPalette,
  elPortalPalette,
  nfPortalPalette,
  bsmnPortalPalette,
  stopAdPortalPalette,
  digitalHealthPortalPalette,
  crcResearcherPortalPalette,
  cancerComplexityPortalPalette,
  sageBionetworksPalette,
  geniePalette,
  standardsPortalPalette,
  ampalsPalette,
  classicPalette,
} from './Palettes'

export default {
  palette,
  generatePalette,
  adKnowledgePortalPalette,
  mtbPalette,
  arkPortalPalette,
  challengePortalPalette,
  elPortalPalette,
  nfPortalPalette,
  bsmnPortalPalette,
  stopAdPortalPalette,
  digitalHealthPortalPalette,
  crcResearcherPortalPalette,
  cancerComplexityPortalPalette,
  sageBionetworksPalette,
  geniePalette,
  standardsPortalPalette,
  ampalsPalette,
  classicPalette,
}
