import ARKWelcomePage from '@sage-bionetworks/synapse-portal-framework/components/arkportal/ARKWelcomePage'
import { SectionLayout } from '@sage-bionetworks/synapse-portal-framework/components/SectionLayout'
import { Goals } from 'synapse-react-client/components/Goals'
import { JsonLdScript } from 'synapse-react-client/components/JsonLdScript'

function Home() {
  return (
    <>
      <JsonLdScript
        thing={{
          '@context': 'https://schema.org',
          '@type': 'Dataset',
          '@id': 'https://arkportal.synapse.org/',
          // "http://purl.org/dc/terms/conformsTo": {
          //     "@type": "CreativeWork",
          //     "@id": "https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE-2019_07_01/"
          // },
          keywords: [
            'arthritis',
            'autoimmune disease',
            'lupus nephritis',
            'lupus',
            'systemic lupus erythematosus',
            'rheumatoid arthritis',
            'accelerating medicines partnership',
            'vitiligo',
            'cutaneous lupus erythematosus',
            'scleroderma',
            'dermatomyositis',
            'Sjogren’s disease',
            "Sjogren's",
            "Sjogren's syndrome",
            'psoriasis',
            'psoriatic arthritis',
            'National Institute of Arthritis and Musculoskeletal and Skin Diseases',
            'NIAMS',
            'Foundation for the National Institutes of Health',
            'FNIH',
            'National Institute of Allergy and Infectious Diseases',
            'NIAID',
            'Human Data',
            'Life Sciences',
            'biomedical data',
          ],
          description:
            'The ARK Portal is a public data repository that stores and shares data and research knowledge generated by a network of research teams focused on arthritis and autoimmune and related diseases.',
          name: 'Arthritis and Autoimmune and Related Diseases Knowledge Portal',
          provider: {
            '@type': 'Organization',
            name: 'Sage Bionetworks',
            url: 'https://www.synapse.org/',
          },
          alternateName: 'ARK Portal',
        }}
      />
      <ARKWelcomePage />
      <SectionLayout>
        <Goals entityId={'syn38103451'} />
      </SectionLayout>
    </>
  )
}

export default Home
