import * as SynapseComponents from './components'
import {
  AccessTokenPage,
  CardConfiguration,
  type CardContainerLogicProps,
  CardLink,
  CertificationQuiz,
  ChallengeDataDownload,
  type ChallengeDataDownloadProps,
  ChallengeDetailPage,
  ChallengeSubmission,
  ChangePassword,
  ChangePasswordWithToken,
  ClickCallbackParams,
  ColumnIconConfigs,
  ConfirmationDialog,
  CookiePreferencesDialog,
  CookiesNotification,
  CustomControlCallbackData,
  type DatasetJsonLdScriptProps,
  DiscussionThread,
  displayToast,
  type DownloadCartPageProps,
  ExperimentalMode,
  type ExternalFileHandleLinkProps,
  type FeaturedDataTabsProps,
  FeaturedToolsList,
  FileUpload,
  ForumPage,
  FullWidthAlert,
  generateEncodedPathAndQueryForSelectedFacetURL,
  GenericCardSchema,
  type GoalsProps,
  GraphItem,
  IconName,
  IconOptions,
  IconSvg,
  LabelLinkConfig,
  LastLoginInfo,
  LockedColumn,
  LoginMethod,
  type MarkdownCollapseProps,
  type MarkdownSynapseProps,
  MuiContainer,
  NoContentPlaceholderType,
  OAuthClientManagement,
  type OrientationBannerProps,
  PasswordField,
  type ProgramsProps,
  ProjectIcon,
  QueryContextConsumer,
  QueryContextType,
  QueryWrapper,
  QueryWrapperPlotNav,
  QueryWrapperPlotNavProps,
  type QueryWrapperProps,
  QueryWrapperSynapsePlotProps,
  QueryWrapperSynapsePlotRowClickEvent,
  RegisterPageLogoutPrompt,
  type ResourcesProps,
  type RssFeedCardsProps,
  ShowMore,
  SkeletonTable,
  StandaloneLoginForm,
  type StandaloneQueryWrapperProps,
  StyledFormControl,
  StyledOuterContainer,
  SubscriptionPage,
  type SubsectionRowRendererProps,
  SynapseErrorBoundary,
  type SynapseFormSubmissionGridProps,
  type SynapseFormWrapperProps,
  type SynapsePlotProps,
  SynapseToastContainer,
  SystemUseNotification,
  type TableFeedCardsProps,
  TargetEnum,
  TermsAndConditions,
  type ThemesPlotProps,
  type TimelinePlotProps,
  TwoFactorAuthSettingsPanel,
  TwoFactorBackupCodes,
  TwoFactorEnrollmentForm,
  type UpsetPlotProps,
  useLastLoginInfo,
  useLastLoginInfoState,
  useQueryContext,
  UserCard,
  type UserCardListGroupsProps,
  type UserCardListRotateProps,
  type UserCardProps,
  UserOrTeamBadge,
} from './components'
import * as SynapseTheme from './theme'
import Palettes from './theme/palette/Palettes'
import {
  OAuth2State,
  preparePostSSORedirect,
  redirectAfterSSO,
  SynapseClientError,
  SynapseConstants,
  SynapseContextConsumer,
  SynapseContextProvider,
  SynapseContextType,
  SynapseHookUtils,
  SynapseUtilityFunctions,
  useApplicationSessionContext,
  useFramebuster,
  useQuerySearchParam,
  useSynapseContext,
} from './utils'
import FullContextProvider, {
  defaultQueryClientConfig,
} from './utils/context/FullContextProvider'
import * as AppUtils from './utils/AppUtils'
import * as RegularExpressions from './utils/functions/RegularExpressions'
import SynapseClient, { HttpClient } from './synapse-client'
import * as SynapseQueries from './synapse-queries'
import GoogleMap from './components/GoogleMap'
import {
  ApplicationSessionManager,
  ApplicationSessionManagerProps,
} from './utils/AppUtils/session/ApplicationSessionManager'

const SynapseContextUtils = {
  SynapseContextProvider,
  SynapseContextConsumer,
  useSynapseContext,
  FullContextProvider,
  defaultQueryClientConfig,
}

export {
  // Core Synapse functionality
  SynapseClient,
  SynapseClientError,
  SynapseConstants,
  SynapseQueries,
  SynapseUtilityFunctions,

  // Context and Hooks
  SynapseContextUtils,
  SynapseHookUtils,
  useApplicationSessionContext,
  useFramebuster,
  useLastLoginInfo,
  useLastLoginInfoState,
  useQueryContext,
  useQuerySearchParam,
  useSynapseContext,

  // Components and their associated types
  ApplicationSessionManager,
  type ApplicationSessionManagerProps,
  ChallengeDataDownload,
  type ChallengeDataDownloadProps,
  ChallengeDetailPage,
  ChallengeSubmission,
  ConfirmationDialog,
  CookiesNotification,
  DiscussionThread,
  ExperimentalMode,
  FeaturedToolsList,
  FileUpload,
  ForumPage,
  FullContextProvider,
  FullWidthAlert,
  IconSvg,
  GoogleMap as Map,
  LastLoginInfo,
  MuiContainer,
  PasswordField,
  ProjectIcon,
  QueryContextConsumer,
  type QueryContextType,
  QueryWrapper,
  QueryWrapperPlotNav,
  type QueryWrapperPlotNavProps,
  type QueryWrapperSynapsePlotProps,
  type QueryWrapperSynapsePlotRowClickEvent,
  ShowMore,
  SkeletonTable,
  StandaloneLoginForm,
  StyledFormControl,
  StyledOuterContainer,
  SubscriptionPage,
  SystemUseNotification,
  SynapseContextConsumer,
  SynapseContextProvider,
  SynapseErrorBoundary,
  SynapseToastContainer,
  TargetEnum,
  UserCard,
  UserOrTeamBadge,

  // Utilities & Miscellaneous
  AppUtils,
  displayToast,
  defaultQueryClientConfig,
  generateEncodedPathAndQueryForSelectedFacetURL,
  HttpClient,
  NoContentPlaceholderType,
  Palettes,
  preparePostSSORedirect,
  redirectAfterSSO,
  RegularExpressions,
  SynapseComponents,
  SynapseTheme,

  // Prop types closely associated with components
  type CardConfiguration,
  type CardContainerLogicProps,
  type CardLink,
  type ClickCallbackParams,
  type ColumnIconConfigs,
  type CustomControlCallbackData,
  type DatasetJsonLdScriptProps,
  type DownloadCartPageProps,
  type ExternalFileHandleLinkProps,
  type FeaturedDataTabsProps,
  type GenericCardSchema,
  type GoalsProps,
  type GraphItem,
  type IconName,
  type IconOptions,
  type LabelLinkConfig,
  type LockedColumn,
  type LoginMethod,
  type MarkdownCollapseProps,
  type MarkdownSynapseProps,
  type OrientationBannerProps,
  type ProgramsProps,
  type QueryWrapperProps,
  type ResourcesProps,
  type RssFeedCardsProps,
  type StandaloneQueryWrapperProps,
  type SubsectionRowRendererProps,
  type SynapseContextType,
  type SynapseFormSubmissionGridProps,
  type SynapseFormWrapperProps,
  type SynapsePlotProps,
  type TableFeedCardsProps,
  type ThemesPlotProps,
  type TimelinePlotProps,
  type UpsetPlotProps,
  type UserCardListGroupsProps,
  type UserCardListRotateProps,
  type UserCardProps,

  // Authentication and Security Components
  AccessTokenPage,
  CertificationQuiz,
  ChangePassword,
  ChangePasswordWithToken,
  CookiePreferencesDialog,
  OAuthClientManagement,
  RegisterPageLogoutPrompt,
  TermsAndConditions,
  TwoFactorAuthSettingsPanel,
  TwoFactorBackupCodes,
  TwoFactorEnrollmentForm,
  type OAuth2State,
}
