import { AddAlertTwoTone } from '@mui/icons-material'
import { Link } from '@mui/material'
import { HomePageHeaderConfig } from '@sage-bionetworks/synapse-portal-framework/types/portal-config'

const homePageHeader: HomePageHeaderConfig = {
  summary: (
    <>
      Discover and explore multi-omic data, integrative analytical tools, and
      resources generated by the National Institute on Aging (NIA) supported
      exceptional longevity studies of protective cellular factors that enhance
      health and life span.
      <Link
        href="https://news.eliteportal.org/elite-portal-newsletter/"
        target="_blank"
        sx={{
          color: 'white',
          '&:hover': { color: 'white', textDecorationColor: 'white' },
          '&:focus': { color: 'white' },
          textDecorationColor: 'white',
          marginTop: '15px',
          display: 'block',
        }}
      >
        <AddAlertTwoTone
          sx={{ width: '24px', height: '24px', mb: '-5px', mr: '7px' }}
        />
        Subscribe to the ELITE Portal Newsletter
      </Link>
    </>
  ),
  title:
    'Welcome to the Exceptional Longevity Translational Resources (ELITE) Portal',
}

export default homePageHeader
