import React from 'react'
import { HomePageHeaderConfig } from 'types/portal-config'

const homePageHeader: HomePageHeaderConfig = {
  summary: (
    <>
      Discover and explore exceptional longevity data, analyses, and tools
      generated by the translational longevity research projects supported by
      the National Institute on Aging (NIA).
    </>
  ),
  title:
    'Welcome to the Exceptional Longevity Translational Resources (ELITE) Portal',
  subscriptionConfig: {
    text: 'Subscribe to the ELITE Portal Newsletter',
    url: 'https://news.eliteportal.org/elite-portal-newsletter/',
  },
}

export default homePageHeader
