export const STUDY_DETAILS_PAGE_DETAILS_TAB_PATH = 'Details'
export const STUDY_DETAILS_PAGE_DATASETS_TAB_PATH = 'Datasets'
export const STUDY_DETAILS_PAGE_FILES_TAB_PATH = 'Files'
export const STUDY_DETAILS_PAGE_ADDITIONAL_FILES_TAB_PATH = 'AdditionalFiles'

export const TOOLS_DETAILS_PAGE_DETAILS_TAB_PATH = 'Details'
export const TOOLS_DETAILS_PAGE_OBSERVATIONS_TAB_PATH = 'Observations'
export const TOOLS_DETAILS_PAGE_DATA_TAB_PATH = 'Data'

export const HACKATHONS_DETAILS_PAGE_BACKGROUND_AND_RESULTS_TAB_PATH =
  'Background&Results'
export const HACKATHONS_DETAILS_PAGE_METHODOLOGY_TAB_PATH = 'Methodology'

export const ORGANIZATION_DETAILS_TAB_PATH = 'Details'
export const ORGANIZATION_STUDIES_TAB_PATH = 'Studies'
export const ORGANIZATION_DATASETS_TAB_PATH = 'Datasets'
export const ORGANIZATION_PUBLICATIONS_TAB_PATH = 'Publications'
export const ORGANIZATION_ANALYTICS_TAB_PATH = 'Analytics'
