// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/ChangePasswordInterface.html
import { TwoFactorAuthOtpType } from './TwoFactorAuthLoginRequest'

export type ChangePasswordInterface = {
  newPassword: string // The new password,
  concreteType: string
}

// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/ChangePasswordWithCurrentPassword.html
// Change user account's password by verifying the current password
export type ChangePasswordWithCurrentPassword = {
  newPassword: string // The new password
  concreteType: string
  username: string // The user's username
  currentPassword: string // The user's password
  authenticationReceipt?: string // Optional, but highly recommended. The most recent authentication receipt given to the last success login from this machine, using this client. Having this allows you to bypass throttling on consecutive authentication attempts with a wrong password.
}

// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/ChangePasswordWithToken.html
// Change user account's password by providing a token issued by the server
export type ChangePasswordWithToken = {
  newPassword: string
  concreteType: string
  passwordChangeToken: PasswordResetSignedToken
}

// https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/PasswordResetSignedToken.html
// Signed token containing the the information necessary to reset the password for a user.
export type PasswordResetSignedToken = {
  concreteType: string
  hmac: string // The hash message authentication code for the message.
  version: number // The version of the key used to generate the HMAC.
  expiresOn: string // The date-time when this token expires.
  createdOn: string // The date-time the token was generated.
  userId: string // The ID of the user account.
  validity: string // Used to check if this token is valid
}

/**
 * Used to change the user password when two-factor authentication is enabled. The twoFaToken is generated by the server and included in the 401 response the user tries to update the password with either the old password or a token. Only TOTP and RECOVERY_CODE otp codes can be used for this operation.
 * http://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/ChangePasswordWithTwoFactorAuthToken.html
 */
export type ChangePasswordWithTwoFactorAuthToken = {
  /* The new password */
  newPassword: string
  /* Indicates which implementation of PasswordChangeInterface this object represents. Valid Values: org.sagebionetworks.repo.model.auth.ChangePasswordWithToken org.sagebionetworks.repo.model.auth.ChangePasswordWithCurrentPassword */
  concreteType: string
  /* The id of the user that attempted to authenticate. */
  userId: number
  /* The token that was included in the error response when authenticating. */
  twoFaToken: string
  /* One time password (e.g. generated by the authenticator application, depending on the otpType value) */
  otpCode: string
  /* The type of one time password code that can be used to authenticate through two-factor authentication. */
  otpType: TwoFactorAuthOtpType
}
