export type FeatureFlags = Record<FeatureFlagEnum, boolean>

export enum FeatureFlagEnum {
  DESCRIPTION_FIELD = 'DESCRIPTION_FIELD',
  CHANGE_PASSWORD_2FA_CHECK = 'CHANGE_PASSWORD_2FA_CHECK',
  VIRTUALTABLE_SUPPORT = 'VIRTUALTABLE_SUPPORT',
  JSONSCHEMA_VALIDATION_STATUS = 'JSONSCHEMA_VALIDATION_STATUS',
}
