/**
 * https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/TotpSecret.html
 */
export type TotpSecret = {
  /* The id of the generated secret */
  secretId: string
  /* The base32 encoded secret */
  secret: string
  /* The algorithm used for the TOTP */
  alg: string
  /* Number of digits for the TOTP */
  digits: number
  /* The validity period for the TOTP */
  period: number
  /* The username of the calling user. Can be used to display a friendly name in an authenticator app. */
  username: string
}

/**
 * https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/TotpSecretActivationRequest.html
 */
export type TotpSecretActivationRequest = {
  /* The id of the secret */
  secretId: string
  /* The code generated by the authenticator application */
  totp: string
}

export type TwoFactorAuthStatus = {
  status: 'ENABLED' | 'DISABLED'
}
