/**
 * Used to log in when two-factor authentication is enabled.
 *
 * https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/auth/TwoFactorAuthLoginRequest.html
 */
export type TwoFactorAuthLoginRequest = {
  /* The id of the user that attempted to authenticate. */
  userId: number
  /* The token that was included in the error response when authenticating. */
  twoFaToken: string
  /* One time password (e.g. generated by the authenticator application, depending on the otpType value) */
  otpCode: string
  /* The type of one time password code that can be used to authenticate through two-factor authentication. */
  otpType: TwoFactorAuthOtpType
}

export type TwoFactorAuthOtpType = 'TOTP' | 'RECOVERY_CODE'
