import {
  ADDITIONAL_PROPERTY_FLAG,
  FormContextType,
  RJSFSchema,
  StrictRJSFSchema,
  TranslatableString,
  WrapIfAdditionalTemplateProps,
} from '@rjsf/utils'
import { FocusEventHandler, useEffect, useState } from 'react'
import { Grid, TextField } from '@mui/material'

/** The `WrapIfAdditional` component is used by the `FieldTemplate` to rename, or remove properties that are
 * part of an `additionalProperties` part of a schema.
 *
 * @param props - The `WrapIfAdditionalProps` for this component
 */
export default function SynapseAnnotationsWrapIfAdditionalTemplate<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any,
>(props: WrapIfAdditionalTemplateProps<T, S, F>) {
  const {
    id,
    classNames,
    disabled,
    label,
    onKeyChange,
    readonly,
    required,
    schema,
    children,
    registry,
  } = props
  const { translateString } = registry
  const keyLabel = translateString(TranslatableString.KeyLabel, [''])

  const additional = ADDITIONAL_PROPERTY_FLAG in schema
  const isAutoGenerated = /^newKey(_?\d+)?$/.test(label)

  const [initializedId, setInitializedId] = useState<string | null>(null)
  const [keyValue, setKeyValue] = useState('')

  useEffect(() => {
    if (additional && initializedId !== id) {
      setInitializedId(id)
      if (isAutoGenerated) {
        setKeyValue('') // show placeholder instead
      } else {
        setKeyValue(label) // show actual label for non-new rows
      }
    }
  }, [id, label, additional, initializedId, isAutoGenerated])

  const handleBlur: FocusEventHandler<
    HTMLInputElement | HTMLTextAreaElement
  > = ({ target }) => {
    if (target) onKeyChange(target.value)
  }

  if (!additional) {
    return <div className={classNames}>{children}</div>
  }

  return (
    <div className={classNames}>
      <Grid container my={1} columnSpacing={2} rowSpacing={0}>
        <Grid item xs={3}>
          <TextField
            fullWidth={true}
            required={required}
            label={keyLabel}
            value={keyValue}
            placeholder={label}
            disabled={disabled || readonly}
            id={`${id}-key`}
            name={`${id}-key`}
            onChange={e => setKeyValue(e.target.value)}
            onBlur={!readonly ? handleBlur : undefined}
            type="text"
          />
        </Grid>
        {children}
        {/* All additional properties are treated as arrays, so we don't show a remove button here. */}
        {/* To drop the property, drop the last array item. */}
      </Grid>
    </div>
  )
}
