name: 'Build Storybook'

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    # Run on all events except labeled PRs without the 'chromatic' label
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'chromatic' }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - uses: ./.github/actions/pnpm-setup-action
      - name: Prebuild dependencies
        run: pnpm nx run synapse-react-client:build
      - name: Build Storybook
        run: pnpm nx run synapse-react-client:storybook:build
      - name: Upload Storybook artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: storybook-static
          path: packages/synapse-react-client/storybook-static
          retention-days: 1
