name: 'Deploy synapse-oauth-signin'

on:
  push:
    branches:
      - main
    paths:
      - 'packages/synapse-react-client/**'
      - 'apps/synapse-oauth-signin/**'
jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-deploy-app.yml
    with:
      app-name: synapse-oauth-signin
      branch-or-tag: main
      bucket-name: staging-signin-synapse-websitebucket-d0h9iyfy390u
      cfdist-id: EUE2TU70O0M2M
      deployment-role-arn: arn:aws:iam::325565585839:role/sagebase-github-oidc-synapseprod-web-monorepo-infra
      vite-mode: 'staging'
