name: End to end testing for react-datasheet-grid

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

env:
  PACKAGE_SUBDIR: packages/react-datasheet-grid

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
      - uses: ./.github/actions/pnpm-setup-action
        with:
          STORE_NX_CACHE: 'true'

      - name: Determine if the package has had any changes
        id: package_changes
        run: |
          if pnpm nx show projects --affected --json \
            | jq -e 'index("@sage-bionetworks/react-datasheet-grid")' > /dev/null; then
            echo "Project is affected; setting project_affected=true"
            echo "project_affected=true" >> "$GITHUB_OUTPUT"
          else
            echo "Project is not affected; setting project_affected=false"
            echo "project_affected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Playwright Browsers
        if: ${{ steps.package_changes.outputs.project_affected == 'true' }}
        run: |
          cd "${{ env.PACKAGE_SUBDIR }}"
          pnpm playwright install --with-deps chromium

      - name: Run e2e tests
        if: ${{ steps.package_changes.outputs.project_affected == 'true' }}
        run: pnpm nx run @sage-bionetworks/react-datasheet-grid:e2e

      - name: Upload HTML report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() && steps.package_changes.outputs.project_affected == 'true' }}
        with:
          name: datasheet-grid-e2e-report--attempt-${{ github.run_attempt }}
          path: '${{ env.PACKAGE_SUBDIR }}/playwright-report'
          retention-days: 14
