name: 'Publish Storybook to GitHub Pages'

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/pnpm-setup-action
      - name: Build Storybook
        run: pnpm nx run synapse-react-client:storybook:build
      - name: Create .nojekyll file for GitHub Actions
        run: touch packages/synapse-react-client/storybook-static/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: packages/synapse-react-client/storybook-static
